"""expand tenant management

Revision ID: 7ec91a17eeb0
Revises: 
Create Date: 2025-11-06 09:14:40.299076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec91a17eeb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if 'tenant_change' not in inspector.get_table_names():
        op.create_table(
            'tenant_change',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('tenant_id', sa.Integer(), nullable=False),
            sa.Column('change_date', sa.Date(), nullable=True),
            sa.Column('description', sa.String(length=255), nullable=False),
            sa.Column('amount_spent', sa.Float(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_index(op.f('ix_tenant_change_tenant_id'), 'tenant_change', ['tenant_id'], unique=False)

    if 'tenant_complaint' not in inspector.get_table_names():
        op.create_table(
            'tenant_complaint',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('tenant_id', sa.Integer(), nullable=False),
            sa.Column('description', sa.Text(), nullable=False),
            sa.Column('status', sa.String(length=20), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('resolved_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_index(op.f('ix_tenant_complaint_tenant_id'), 'tenant_complaint', ['tenant_id'], unique=False)

    if 'tenant_todo' not in inspector.get_table_names():
        op.create_table(
            'tenant_todo',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('tenant_id', sa.Integer(), nullable=False),
            sa.Column('task', sa.String(length=255), nullable=False),
            sa.Column('due_date', sa.Date(), nullable=True),
            sa.Column('is_done', sa.Boolean(), nullable=True),
            sa.Column('completed_at', sa.DateTime(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_index(op.f('ix_tenant_todo_tenant_id'), 'tenant_todo', ['tenant_id'], unique=False)
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_contact', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('secondary_contact', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('agreement_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if 'tenant_todo' in inspector.get_table_names():
        op.drop_index(op.f('ix_tenant_todo_tenant_id'), table_name='tenant_todo')
        op.drop_table('tenant_todo')
    if 'tenant_complaint' in inspector.get_table_names():
        op.drop_index(op.f('ix_tenant_complaint_tenant_id'), table_name='tenant_complaint')
        op.drop_table('tenant_complaint')
    if 'tenant_change' in inspector.get_table_names():
        op.drop_index(op.f('ix_tenant_change_tenant_id'), table_name='tenant_change')
        op.drop_table('tenant_change')

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('agreement_filename')
        batch_op.drop_column('secondary_contact')
        batch_op.drop_column('primary_contact')
    # ### end Alembic commands ###
