name: CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps and run tests
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pytest -q
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          script_stop: true
          script: |
            set -e
            if [ ! -d /opt/rentalai/app ]; then
              sudo mkdir -p /opt/rentalai
              sudo chown -R ${{ secrets.DEPLOY_USER }}:www-data /opt/rentalai
              git clone https://github.com/${{ github.repository }} /opt/rentalai/app
            fi
            cd /opt/rentalai/app
            git fetch --all --prune
            git reset --hard origin/main
            cd rentalai
            if [ ! -d .venv ]; then python3 -m venv .venv; fi
            source .venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            python3 - <<'PY'
from app import create_app
from app.models import db
from flask_migrate import upgrade
app = create_app()
with app.app_context():
    upgrade()
print('Applied migrations (if any).')
PY
            sudo systemctl restart rentalai
            # Smoke check (Gunicorn direct)
            curl -fsS -I http://127.0.0.1:8000/ >/dev/null || (journalctl -u rentalai -n 100 --no-pager; exit 1)
            # Optional: If Nginx is fronting, also verify HTTP 200/302
            if command -v nginx >/dev/null 2>&1; then curl -fsS -I http://localhost/ >/dev/null || true; fi
